# Generated by Django 5.0.6 on 2024-09-04 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_alter_libro_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='isbn',
        ),
    ]
