# Generated by Django 5.0.6 on 2024-09-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0005_libro_isbn_alter_autor_id_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
